### PR TITLE
Update to swift 5 and ReactiveSwift 6 🎉

### PR DESCRIPTION
**Pull request by portellaa**
* Updated version of swift to 5
* Updated Carthage and Podfile dependencies to use ReactiveSwift 6 and ReactiveCocoa 10
* Removed Result from dependencies
* Changed all `NoError` to `Never`
* Updated `ReactiveFeedbackTests-tvOS` base SDK to tvOS

### CODE REVIEW

**Comment by andersio** [comment]
Seems we need to fix something to get CocoaPods working. :(

**Comment by portellaa** [comment]
I managed to get this working with cocoapods beta.
I tried to add `swift_version` to the podspec, but it also didn’t work.

Do you have an idea how to get this working? 😕

**Comment by eimantas** [comment]
Any ETA on this PR? I'd love to use it with RAS6.

**Comment by portellaa** [comment]
The circleci pipeline is not running `bundle install` as one of the build steps. 

Shouldn't this be one of the steps to configure the necessary environment?

**Comment by diegopetrucci** [comment]
cc @ilyapuchka @AliSoftware

**Comment by diegopetrucci** [comment]
The repo has indeed been migrated to Swift 5, so I'm closing this https://github.com/Babylonpartners/ReactiveFeedback/commit/6a6d64172443d45db5e07b6fd6d1708f78aa7c19

**Pull request closed without merging**
