### PR TITLE
`Example` cannot be shared otherwise it's built by Carthage

### PR DESCRIPTION
**Pull request by dmcrodrigues**
`ReactiveFeedback`'s Example scheme was marked as `Shared` in 0.4.0 and because of that is being built by Carthage leading to a failure since `ReactiveCocoa` and `Kingfisher` are not official dependencies of ReactiveFeedback and because of that they are not pulled and built to link with `Example`.

Any project trying to include the latest version of `ReactiveFeedback` will fail unless they have `ReactiveCocoa` and `Kingfisher` in their `Cartfile`.

This may break CI but we need to find a way to build `Example` without having a shared scheme.

### CODE REVIEW

**Comment by eimantas** [comment]
I'm currently experiencing this exact issue.

**Comment by andersio** [comment]
@dmcrodrigues should we remove the example app from CI for now?

**Comment by dmcrodrigues** [comment]
@andersio that's probably the best solution for now, shall I proceed with that change?

**Comment by sergdort** [comment]
> should we remove the example app from CI for now?

Not cool :)

**Comment by diegopetrucci** [comment]
Any news on this, or should we close the PR?

**Pull request closed without merging**
