### PR TITLE
Create podspec. Reconfigure the project for Carthage, Xcode support and CI.

### LINKED ISSUE #4: Carthage and Xcode support.

### PR DESCRIPTION
**Pull request by andersio**
Fixes #4 
1. Create a podspec.

2. Reconfigure the ReactiveFeedback framework to be a universal framework scheme that supports iOS 8.0+, macOS 10.9+, watchOS 2.0+ and tvOS 9.0+.

Sadly, Carthage was pulled in for the development environment in because CocoaPods refuses to yield per platform framework targets for the same pod. 💁‍♂️

### CODE REVIEW

**Comment by sergdort** [comment]
I think we just need to make several development frameworks e.g `ReactiveFeedback-iOS`, `ReactiveFeedback-tvOS` etc. And make the same module name for all

**Review by sergdort — CHANGES_REQUESTED** [review]
TBH I'm against using `Carthage` for development as it requires additional steps to play with it. 
Also, I'm pretty sure that not all developers have `Carthage ` installed, like me :)

**Comment by andersio** [comment]
So should we use CocoaPods? Or just git submodules?

**Comment by sergdort** [comment]
Not sure, TBH I've never used `git submodules`

**Comment by RuiAAPeres** [comment]
Cocoapods + Carthage?

**Comment by andersio** [comment]
@RuiAAPeres We already support both, plus those who use the Xcode project directly. The question is what workspace i.e. the example app and the test targets should use.

> I think we just need to make several development frameworks e.g ReactiveFeedback-iOS, ReactiveFeedback-tvOS etc. 

@sergdort ~~If you mean doing this for CocoaPods, that would tie the framework target with CocoaPods. I have tried declaring abstract target per platform, and CocoaPods just create an iOS target (for the example app). :S~~

**Comment by andersio** [comment]
https://github.com/Moya/Moya
^ Similar example: Moya

Edit: https://github.com/RxSwiftCommunity/RxDataSources
^ This seems to be a way to support both Carthage & CocoaPods.

**Comment by andersio** [comment]
I can add a Podfile. But note that it would require us to actively prevent CocoaPods modified Xcode project from being merged.

**Comment by andersio** [comment]
So now it should support both CocoaPods and Carthage for development. I guess it should be sufficient given our example sets would probably remain iOS exclusive, and the framework would hardly have platform specific logic by its nature.

**Comment by sergdort** [comment]
LGTM 👍

**Review by sergdort — APPROVED** [review]

**Pull request merged**
